version: '2'
services:
  db:
    image: mariadb:10.4
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./.data/db:/var/lib/mysql
    ports:
      - 3306:3306
  web:
    image: ubcctlt/mediawiki
    build: .
    ports:
      - 8080:80
    # use the links section if you want to use a container for a database.
    # if not, and you want to use an external database server, configure
    # if with the environment variables in the 'environment' section.
    # see README.md for more details.
    links:
      - db
    # uncomment the 'volumes' section to enable a shared volume with docker-compose
    volumes:
      - ./.data/web:/data:rw
      - ./CustomSettings.php:/conf/CustomSettings.php
      # do not uncomment this when starting a new instance from scratch as
      # init script won't be able to move this file
      #- ./LocalSettings.php:/var/www/html/LocalSettings.php
    environment:
      - MEDIAWIKI_SITE_SERVER=http://localhost:8080
      - MEDIAWIKI_SITE_NAME=My Awesome Wiki
      - MEDIAWIKI_DB_HOST=db
      - MEDIAWIKI_DB_PASSWORD=password
      # uncomment 'MEDIAWIKI_ENABLE_SSL' to enable SSL support
      # - MEDIAWIKI_ENABLE_SSL=true
      - MEDIAWIKI_EXTENSIONS=VisualEditor,WikiEditor,ParserFunctions,Cite,TemplateData,Scribunto,InputBox,Widgets,Maps,Math,LiquidThreads,Variables,RightFunctions,PageInCat,CategoryTree,LabeledSectionTransclusion,UserPageEditProtection,Quiz,UploadWizard,Collection,DynamicPageList,EmbedPage,UWUBCMessages,GoogleAnalyticsMetrics,googleAnalytics,Renameuser,caliper,DeleteBatch,LinkTarget,UBCAuth
      - MEDIAWIKI_ALLOW_SITE_CSS_ON_RESTRICTED_PAGES=true
      - PARSOID_URL=http://nodeservices:8142
      - PARSOID_DOMAIN=localhost
      - RESTBASE_URL=http://nodeservices:7231
      - LDAP_DOMAIN=CWL
      - LDAP_SERVER=ldap
      - LDAP_ENCRYPTION_TYPE=clear
      - LDAP_SEARCH_ATTRS=cn
      - LDAP_PROXY_AGENT=cn=admin,dc=example,dc=org
      - LDAP_PROXY_PASSWORD=admin
      - LDAP_BASE_DN=dc=example,dc=org
      - LDAP_USER_BASE_DN=dc=example,dc=org
      - LDAP_USERNAME_ATTR=cn
      - LDAP_REALNAME_ATTR=displayname
      - LDAP_EMAIL_ATTR=mail
      - LDAP_NEW_USER_REDIRECT_TO=UBC_Wiki:Welcome
      #- MEDIAWIKI_MAIN_CACHE=CACHE_MEMCACHED
      - MEDIAWIKI_MAIN_CACHE=CACHE_NONE
      #- MEDIAWIKI_MEMCACHED_SERVERS=["memcached:11211"]
      # uncomment to specify the wgUploadPath
      # - MEDIAWIKI_UPLOAD_PATH=
      #- GOOGLE_ANALYTICS_UA=UA-XXXXXXX-XX
      # GoogleAnalyticsMetrics: https://www.mediawiki.org/wiki/Extension:GoogleAnalyticsMetrics
      #- GOOGLE_ANALYTICS_METRICS_ALLOWED
      #- GOOGLE_ANALYTICS_METRICS_PATH
      #- GOOGLE_ANALYTICS_METRICS_VIEWID
      - DEBUG=true
      # - CaliperHost=https://caliper.imsglobal.org/caliper/PUT_TEST_BEARER_TOKEN_HERE/message
      # - CaliperAPIKey=PUT_TEST_BEARER_TOKEN_HERE
      # - CaliperAppBaseUrl=http://localhost:8888/test_url/
      # - CaliperLDAPActorHomepage=http://media_wiki_ldap_homepage

# use combined image for now
#  parsoid:
#    image: ubcctlt/parsoid
#    environment:
#      - MEDIAWIKI_API_URL=http://web/w/api.php
#      - MEDIAWIKI_DOMAIN=localhost
#      - MEDIAWIKI_PREFIX=localhost
#  restbase:
#    image: ubcctlt/restbase
#    environment:
#      - MEDIAWIKI_API_URL=http://web/w/api.php
#      - PARSOID_DOMAIN=localhost
#      - PARSOID_URL=http://parsoid:8000
  nodeservices:
    image: ubcctlt/mediawiki-node-services
    ports:
      - 7231:7231
    environment:
      - MEDIAWIKI_API_URL=http://web/api.php
      - LOG_LEVEL=debug
    volumes:
      - ./.data/services:/data
  ldap:
    image: osixia/openldap:1.1.9
    command: --copy-service
    ports:
      - 1389:389
    volumes:
      - ./dev/ldapadd_ubcedu.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/ldapadd_ubcedu.ldif
      - ./.data/ldap:/var/lib/ldap
      - ./.data/slapd.d:/etc/ldap/slapd.d
  memcached:
    image: memcached:1.5-alpine
